### ISSUE TITLE
Account invoice grouped by picking- error en la impresión

### ISSUE THREAD

**Issue by afilomeno** [OCA/account-invoice-reporting#108]
Hemos instalado el módulo y nos encontramos que cuando hay una devolución de un producto no nos detalla el abarán ni de devolución ni de origen y a la vez, el importe total de las cantidades devueltas no es correcto y para los clientes no queda nada claro, porqué sólo sale la cantidad en negativo, pero en el total de la linea no. 
Agradecería si alguien nos pudiera ayudar. 
![Capturafrade](https://user-images.githubusercontent.com/33481290/56971418-7c244280-6b69-11e9-88e6-3dbb8faf27ed.JPG)

**Comment by pedrobaeza** [comment]
Please, only in English, and the problem is in stock_picking_invoice_link, not here. Check if you have https://github.com/OCA/stock-logistics-workflow/pull/445.
