### ISSUE TITLE
[12.0] account_invoice_report_grouped_by_picking: after update the old invoices don't are grouped

### ISSUE THREAD

**Issue by josepmy** [OCA/account-invoice-reporting#145]
Hi,
After update account_invoice_report_grouped_by_picking, if you try to print again an invoice created before the module update, the groups by picking don't appear but on the newly created invoices appear fine.
The old invoices appear without any kind of group.
No error or warning into the log when update.

What is missing?

**Comment by pedrobaeza** [comment]
Yes, that's something expected, as the links can't be magically restored if doesn't exist before. Anyway, this is something of `stock_picking_invoice_link` module, not this one.

**Comment by josepmy** [comment]
ok. Thanks.
