### ISSUE TITLE
[13] Community  account_invoice_report_grouped_by_picking report issue

### ISSUE THREAD

**Issue by sergioeix** [OCA/account-invoice-reporting#158]
When you make a RINV on the report quantity its dupliated like you can see on this screenshots:
![image](https://user-images.githubusercontent.com/62206774/98707178-07e27600-2380-11eb-9400-f8b4428329ac.png)
Lets make the partial RINV:
![image](https://user-images.githubusercontent.com/62206774/98707305-2ba5bc00-2380-11eb-9448-696dd90431e7.png)
And then lets print report from RINV:
![image](https://user-images.githubusercontent.com/62206774/98708350-580e0800-2381-11eb-9787-a08402a121da.png)
Total amount its fine but the quantity marked its double, i dont know why all this section is there or i am not getting the point; i think that it could be removed and show only the returned quantity.
![image](https://user-images.githubusercontent.com/62206774/98707974-ecc43600-2380-11eb-8a11-d54255335b03.png)

B/R

**Comment by miguel-S73** [comment]
I have detected the same problem in odoo 14. Has anyone already given a solution?
