### ISSUE TITLE
[12] partner_time_to_pay

### ISSUE THREAD

**Issue by diggy128** [OCA/account-invoice-reporting#225]
## Module
partner_time_to_pay

## Describe the bug
1) Payable and receivable are inverted: It should be **receivables** from _clients_ and **payable** to _suppliers_
2) date_due in calculations is taken from date_invoice NOT from date_due in invoice
3) Payments for invoice is taken from invoice.payment_ids which is NOT guaranteed to have all invoices that were reconciled (in the reverse field in account.payment help string mentions "This does not especially correspond to the invoices reconciled with the payment, as it can have been generated first, and reconciled later"

## To Reproduce
**Affected versions**:
12.0.1.0.0

1. Check partner form view
2. Check res_partner.py line 50
3. Check res_partner.py lines 53-54

**Expected behavior**
Above points should be corrected and payments should be aggregated from reconciled payments NOT from invoice.payment_ids

**Comment by rafaelbn** [comment]
@max3903 @Shide I confirm this. We should fix it.

We are going to fix it in v15, @Shide is opening an issue.

We are worry for your customers which are running the module in production.

I was installing in production now when I realize about the bug.

So, which is the best way to solve it?

**Comment by rafaelbn** [comment]
For me the bug is

- [x] > 1. Payable and receivable are inverted: It should be receivables from clients and payable to suppliers

This is not a BUG but a improvement for this module or an additional one like partner_time_to_pay_due_date

- [ ] > 2. date_due in calculations is taken from date_invoice NOT from date_due in invoice

The last point, I should review in deeper.

- [x] > 3. Payments for invoice is taken from invoice.payment_ids which is NOT guaranteed to have all invoices that were reconciled (in the reverse field in account.payment help string mentions "This does not especially correspond to the invoices reconciled with the payment, as it can have been generated first, and reconciled later"


We are solving 1. 😄

**Comment by Shide** [comment]
> For me the bug is
> 
> * [ ]  > 1. Payable and receivable are inverted: It should be receivables from clients and payable to suppliers
> 
> This is not a BUG but a improvement for this module or an additional one like partner_time_to_pay_due_date
> 
> * [ ]  > 2. date_due in calculations is taken from date_invoice NOT from date_due in invoice
> 
> The last point, is not a BUG also for me in this moment.
> 
> * [ ]  > 3. Payments for invoice is taken from invoice.payment_ids which is NOT guaranteed to have all invoices that were reconciled (in the reverse field in account.payment help string mentions "This does not especially correspond to the invoices reconciled with the payment, as it can have been generated first, and reconciled later"
> 
> We are solving 1. smile

Ponit 3 is fixed on v15 with the migration. Calculation is based when the invoice payment_state changes to "in_payment" or "paid"

**Comment by Shide** [comment]
I'm working on point 1 and 3

**Comment by Shide** [comment]
Done, you can check the PR if you deserve :)

**Comment by rafaelbn** [comment]
Hello @diggy128 ,

Solved for Odoo v15 in https://github.com/OCA/account-invoice-reporting/pull/252

Thank you!

**Comment by diggy128** [comment]
@rafaelbn 
Even though v15 is a few versions away from v12, it's great to see that the community doesn't give up on issues that propapage amongst versions.

Took a glance at the PR and seems to fix the problem but can't post a functional review (fortunately others stepped in) yet as we don't have v15 deployed.

Kudos!

**Comment by rafaelbn** [comment]
@diggy128  You can test in v15 the solution here (admin/admin): http://oca-account-invoice-reporting-15-0-857c7fc06203.runboat.odoo-community.org/web/login

Do you know runboat?
