### ISSUE TITLE
[14.0][RFC] account_invoice_report_due_list: use residual amounts

### ISSUE THREAD

**Issue by dalonsod** [OCA/account-invoice-reporting#234]
**Is your feature request related to a problem?**
When an invoice has already linked payments, due list doesn't show actual pending payment information.

**Describe the solution you'd like**
I have a customer that usually sends invoice document to his customers when some or full payments are already done. In those cases, due list provided by this addon actually shows past information, because initial amounts are listed. He'd prefer only pending amounts and dates to be shown.

**Describe alternatives you've considered**
I have this doubt: should I develop an improvement PR that optionally uses `amount_residual`/`amount_residual_currency` instead of `balance`/`amount_currency` fields (e.g. with a per-invoice flag "show only pending amounts for due list in invoice report"), or a better approach should be making a new addon inheriting this one that adds this feature?

cc @carlosdauden @victoralmau

**Comment by victoralmau** [comment]
Hi,

I think all this could be something interesting to add to `account_invoice_report_due_list` addon.

I think the best thing would be to add a column called "outstanding amount" with the field: `amount_residual` (or `amount_residual_currency` as appropriate).

Best regards.

**Comment by dalonsod** [comment]
Thanks,

I agree with you, for me is a good solution too. I'll make the PR ASAP.

**Comment by dalonsod** [comment]
PR #236 ready to be reviewed, closing this
