### ISSUE TITLE
[15] account_invoice_report_grouped_by_picking not showing picking reference

### ISSUE THREAD

**Issue by fgarcia-humanoide** [OCA/account-invoice-reporting#257]
## Module
account_invoice_report_grouped_by_picking

## Describe the bug
not showing picking reference

## To Reproduce
create invoice from various pickings from same customer

**Affected versions**: 15

see picture

![Screenshot 2023-01-05 06 48 17](https://user-images.githubusercontent.com/7599709/210711930-e3c2de55-80b3-4beb-a477-5a1a446dfbe1.png)

**Comment by pedrobaeza** [comment]
Please reproduce it in runboat.

**Comment by fgarcia-humanoide** [comment]
In runboat works fine, it must be an error on my instalation.

![Screenshot 2023-01-06 09 10 56](https://user-images.githubusercontent.com/7599709/210958814-efd3d5b1-f595-44e0-9352-53a8d58664c8.png)
