### ISSUE TITLE
[15][IMP] account_invoice_discount_display_amount: improve information

### ISSUE THREAD

**Issue by rafaelbn** [OCA/account-invoice-reporting#289]
Hello @manuelregidor  ( @HaraldPanten @ValentinVinagre ),

What do you think about this improvement in this module you did?

![imagen](https://github.com/OCA/account-invoice-reporting/assets/8736623/4f56216f-cb10-4b63-a5dd-e77867237f61)

Thank you for opinions and other point of view 😄 

@moduon @fcvalgar

**Comment by ValentinVinagre** [comment]
I don't see it as bad, it would be necessary to review what it would look like with partial payments.
What is the need for change? Order the concepts?
