### ISSUE TITLE
Can not install on odoo 8

### ISSUE THREAD

**Issue by tkontogi** [OCA/account-invoice-reporting#47]
Hello
Trying to install the invoice module or the just the base module, I get the following error:

```
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:


Element '<xpath expr="//p[@t-if='o.comment']">' cannot be located in parent view

Error context:
View `report_invoice_document_comments`
[view_id: 1506, xml_id: n/a, model: n/a, parent_id: 532]" while parsing None:5, near
<data inherit_id="account.report_invoice_document">
      <xpath expr="//div[contains(@class, 'page')]/table[1]" position="before">
        <p t-if="o.note1">
          <span t-field="o.note1"/>
        </p>
      </xpath>
      <xpath expr="//p[@t-if='o.comment']" position="after">
        <p t-if="o.note2">
          <span t-field="o.note2"/>
        </p>
      </xpath>
    </data>
```

Thank you

**Comment by yvaucher** [comment]
Hello @tkontogi, could you specify the name of the module, there is a dozen of modules in this repository all of them are related to invoice.

**Comment by tkontogi** [comment]
Hello @yvaucher 

To replicate, I removed both modules.

Then first installed base_comment_template without errors.

After, I installed invoice_comment_template that gave the same error.

```
ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Element '<xpath expr="//p[@t-if='o.comment']">' cannot be located in parent view

Error context:
View `report_invoice_document_comments`
[view_id: 1515, xml_id: n/a, model: n/a, parent_id: 532]" while parsing None:5, near
<data inherit_id="account.report_invoice_document">
      <xpath expr="//div[contains(@class, 'page')]/table[1]" position="before">
        <p t-if="o.note1">
          <span t-field="o.note1"/>
        </p>
      </xpath>
      <xpath expr="//p[@t-if='o.comment']" position="after">
        <p t-if="o.note2">
          <span t-field="o.note2"/>
        </p>
      </xpath>
    </data>
```

Thank you

**Comment by tkontogi** [comment]
I copying over the error again, cause it has in this second case some minor differences:

`ParseError: "ValidateError
Field(s) `arch` failed against a constraint: Invalid view definition

Error details:
Element '<xpath expr="//p[@t-if='o.comment']">' cannot be located in parent view

Error context:
View `report_invoice_document_comments`
[view_id: 1515, xml_id: n/a, model: n/a, parent_id: 532]" while parsing None:5, near
<data inherit_id="account.report_invoice_document">
      <xpath expr="//div[contains(@class, 'page')]/table[1]" position="before">
        <p t-if="o.note1">
          <span t-field="o.note1"/>
        </p>
      </xpath>
      <xpath expr="//p[@t-if='o.comment']" position="after">
        <p t-if="o.note2">
          <span t-field="o.note2"/>
        </p>
      </xpath>
    </data>`
