### ISSUE TITLE
New Module: Qweb Invoice Template Designer

### ISSUE THREAD

**Issue by Fuchur777** [OCA/account-invoice-reporting#49]
Discussed here on the mailing list here: [https://odoo-community.org/groups/accounting-28/accounting-47727](https://odoo-community.org/groups/accounting-28/accounting-47727)

Would like to start with a Templated Designer for Qweb focussed on Invoices. As this is a first missing need.
From there we could further build upon this Designer to allow it to be a full Qweb Template Designer.

**Comment by pedrobaeza** [comment]
That module should go to OCA/reporting-engine, but do you have enough JS background for the things that are needed to do?

**Comment by Fuchur777** [comment]
> That module should go to **OCA/reporting-engine**, 

In a second phase maybe but would think it as its invoice focussed first this is the place. But feel free to move it.

>but do **you** have enough JS background for the things that are needed to do?

You as in me, no.
You as in me, my colleagues (and hopefully others), yes.

**Comment by pedrobaeza** [comment]
Cool, if you have some people for doing it. Remember than a generic approach will server for:

* Saving time adapting your changes from version to version.
* Being valid for other documents apart from invoice.
