### ISSUE TITLE
partner_daytopay

### ISSUE THREAD

**Issue by max3903** [OCA/account-invoice-reporting#52]
At @ursais, we have a module to compute some financial statistics for a partner:
* Average number of days to get customer invoices paid (in the current year)
* Average number of days to get customer invoices paid (lifetime)
* Average number of days to pay vendor bills (in the current year)
* Average number of days to pay vendor bills (lifetime)

I think this repository would be the best fit to host it, unless the feature already exists in a module I haven't found.

Any opinion? Interest?

Thanks.

**Comment by JordiBForgeFlow** [comment]
I find the idea interesting. I tend to think that https://github.com/OCA/account-financial-tools would be better. This is not really a report but a KPI.

The link is broken, though.

**Comment by max3903** [comment]
@jbeficent Sorry, private repo... I removed the link.
