### ISSUE TITLE
[11.0] account_invoice_report_grouped_by_picking not compatible with "Section on sales order" option

### ISSUE THREAD

**Issue by HaraldPanten** [OCA/account-invoice-reporting#83]
Hi all,

I realised that selecting the "Section on sales order" option (Sales --> Settings --> Quotations & Orders --> "Section on sales order") the invoice is not being printed as expected.

It's going to be printed just considering this setting --> "Section on sales order".

In my honest opinion, I think that these two options should be compatible.

What do you think?

Thank you so much in advance.

**Comment by pedrobaeza** [comment]
Well, it's difficult to make both compatible. as they reorder the invoice, and then you have to decide which one has most priority. Any way, if you find a way to do it, it's a nice contribution.

**Comment by HaraldPanten** [comment]
Hi @pedrobaeza , thank you for your quick response.

I think that "Section" field should have more priority than SO and picking relation. Because of that, we could show them in different lines similar to, imagine, Title 1 and Title 2.

Maybe we could set the invoice reports with a structure like:

**Section A**
**SO and picking relation**
Invoice line 1
Invoice line 2
Invoice line ....

**SO and picking relation**
Invoice line ...
Invoice line ...

( New page )

**Section B**
**SO and picking relation**
Invoice line ...
Invoice line ...
Invoice line ...

**SO and picking relation**
Invoice line ...
Invoice line ...
Invoice line ...

etc.

Any suggestion?

**Comment by pedrobaeza** [comment]
Well, I think on contrary: first group by picking, and then by section. Any way, the main problem is that you are going down to move line level, so section information is not there.

**Comment by HaraldPanten** [comment]
Probably your option is more clear, you're right. Then you'll be able to group every invoiced pickings with all the lines related to everyone of them.

What about something like:

**SO and picking relation**
**Section A**
invoice line...
invoice line...
invoice line...

**Section B**
invoice line...
invoice line...
invoice line...


**SO and picking relation**
**Section A**
invoice line...
invoice line...

**Section D**
invoice line...
invoice line...

etc.

?

**Comment by pedrobaeza** [comment]
Yeah, you have to preserve the section information when you go up to the move line for sub-grouping by that criteria.
